package org.shjr.ibase4j.mybatis.generator.model;

import java.io.Serializable;

public class SysField implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field.field
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field.field_desc
     *
     * @mbggenerated
     */
    private String fieldDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field.editable
     *
     * @mbggenerated
     */
    private Integer editable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field.id
     *
     * @return the value of sys_field.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field.id
     *
     * @param id the value for sys_field.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field.field
     *
     * @return the value of sys_field.field
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field.field
     *
     * @param field the value for sys_field.field
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field.field_desc
     *
     * @return the value of sys_field.field_desc
     *
     * @mbggenerated
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field.field_desc
     *
     * @param fieldDesc the value for sys_field.field_desc
     *
     * @mbggenerated
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc == null ? null : fieldDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field.editable
     *
     * @return the value of sys_field.editable
     *
     * @mbggenerated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field.editable
     *
     * @param editable the value for sys_field.editable
     *
     * @mbggenerated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }
}