package org.shjr.ibase4j.mybatis.generator.model;

import java.io.Serializable;

public class SysFieldCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.field_id
     *
     * @mbggenerated
     */
    private Integer fieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.code_desc
     *
     * @mbggenerated
     */
    private String codeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.sortno
     *
     * @mbggenerated
     */
    private Integer sortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.editable
     *
     * @mbggenerated
     */
    private Integer editable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.id
     *
     * @return the value of sys_field_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.id
     *
     * @param id the value for sys_field_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.field_id
     *
     * @return the value of sys_field_code.field_id
     *
     * @mbggenerated
     */
    public Integer getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.field_id
     *
     * @param fieldId the value for sys_field_code.field_id
     *
     * @mbggenerated
     */
    public void setFieldId(Integer fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.code
     *
     * @return the value of sys_field_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.code
     *
     * @param code the value for sys_field_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.code_desc
     *
     * @return the value of sys_field_code.code_desc
     *
     * @mbggenerated
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.code_desc
     *
     * @param codeDesc the value for sys_field_code.code_desc
     *
     * @mbggenerated
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.enable
     *
     * @return the value of sys_field_code.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.enable
     *
     * @param enable the value for sys_field_code.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.sortno
     *
     * @return the value of sys_field_code.sortno
     *
     * @mbggenerated
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.sortno
     *
     * @param sortno the value for sys_field_code.sortno
     *
     * @mbggenerated
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.editable
     *
     * @return the value of sys_field_code.editable
     *
     * @mbggenerated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.editable
     *
     * @param editable the value for sys_field_code.editable
     *
     * @mbggenerated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }
}