package org.shjr.ibase4j.mybatis.generator.dao;

import java.util.List;

import org.shjr.ibase4j.mybatis.generator.model.SysField;

public interface SysFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    int insert(SysField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    SysField selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    List<SysField> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysField record);
}