package org.shjr.ibase4j.mybatis.generator.dao;

import java.util.List;

import org.shjr.ibase4j.mybatis.generator.model.SysUserMenu;

public interface SysUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbggenerated
     */
    int insert(SysUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbggenerated
     */
    SysUserMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbggenerated
     */
    List<SysUserMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserMenu record);
}