package org.ibase4j.mybatis.generator.dao;

import java.util.List;

import org.ibase4j.mybatis.generator.model.SysFieldCode;

public interface SysFieldCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    int insert(SysFieldCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    SysFieldCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    List<SysFieldCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFieldCode record);
}