package org.ibase4j.mybatis.generator.model;

import java.io.Serializable;

public class SysCatalog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.id_
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.cascade_id
     *
     * @mbggenerated
     */
    private String cascadeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.root_key
     *
     * @mbggenerated
     */
    private String rootKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.root_name
     *
     * @mbggenerated
     */
    private String rootName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.hotkey_
     *
     * @mbggenerated
     */
    private String hotkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.is_leaf_
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.is_auto_expand
     *
     * @mbggenerated
     */
    private String isAutoExpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.icon_name
     *
     * @mbggenerated
     */
    private String iconName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_catalog.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_catalog
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.id_
     *
     * @return the value of sys_catalog.id_
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.id_
     *
     * @param id the value for sys_catalog.id_
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.cascade_id
     *
     * @return the value of sys_catalog.cascade_id
     *
     * @mbggenerated
     */
    public String getCascadeId() {
        return cascadeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.cascade_id
     *
     * @param cascadeId the value for sys_catalog.cascade_id
     *
     * @mbggenerated
     */
    public void setCascadeId(String cascadeId) {
        this.cascadeId = cascadeId == null ? null : cascadeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.root_key
     *
     * @return the value of sys_catalog.root_key
     *
     * @mbggenerated
     */
    public String getRootKey() {
        return rootKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.root_key
     *
     * @param rootKey the value for sys_catalog.root_key
     *
     * @mbggenerated
     */
    public void setRootKey(String rootKey) {
        this.rootKey = rootKey == null ? null : rootKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.root_name
     *
     * @return the value of sys_catalog.root_name
     *
     * @mbggenerated
     */
    public String getRootName() {
        return rootName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.root_name
     *
     * @param rootName the value for sys_catalog.root_name
     *
     * @mbggenerated
     */
    public void setRootName(String rootName) {
        this.rootName = rootName == null ? null : rootName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.name_
     *
     * @return the value of sys_catalog.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.name_
     *
     * @param name the value for sys_catalog.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.hotkey_
     *
     * @return the value of sys_catalog.hotkey_
     *
     * @mbggenerated
     */
    public String getHotkey() {
        return hotkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.hotkey_
     *
     * @param hotkey the value for sys_catalog.hotkey_
     *
     * @mbggenerated
     */
    public void setHotkey(String hotkey) {
        this.hotkey = hotkey == null ? null : hotkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.parent_id
     *
     * @return the value of sys_catalog.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.parent_id
     *
     * @param parentId the value for sys_catalog.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.is_leaf_
     *
     * @return the value of sys_catalog.is_leaf_
     *
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.is_leaf_
     *
     * @param isLeaf the value for sys_catalog.is_leaf_
     *
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.is_auto_expand
     *
     * @return the value of sys_catalog.is_auto_expand
     *
     * @mbggenerated
     */
    public String getIsAutoExpand() {
        return isAutoExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.is_auto_expand
     *
     * @param isAutoExpand the value for sys_catalog.is_auto_expand
     *
     * @mbggenerated
     */
    public void setIsAutoExpand(String isAutoExpand) {
        this.isAutoExpand = isAutoExpand == null ? null : isAutoExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.icon_name
     *
     * @return the value of sys_catalog.icon_name
     *
     * @mbggenerated
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.icon_name
     *
     * @param iconName the value for sys_catalog.icon_name
     *
     * @mbggenerated
     */
    public void setIconName(String iconName) {
        this.iconName = iconName == null ? null : iconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_catalog.sort_no
     *
     * @return the value of sys_catalog.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_catalog.sort_no
     *
     * @param sortNo the value for sys_catalog.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }
}