package org.ibase4j.mybatis.generator.model;

import java.io.Serializable;

public class SysDic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.id_
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.index_id
     *
     * @mbggenerated
     */
    private Integer indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.code_
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.code_text
     *
     * @mbggenerated
     */
    private String codeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.enable_
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.editable_
     *
     * @mbggenerated
     */
    private Integer editable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.remark_
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.id_
     *
     * @return the value of sys_dic.id_
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.id_
     *
     * @param id the value for sys_dic.id_
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.index_id
     *
     * @return the value of sys_dic.index_id
     *
     * @mbggenerated
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.index_id
     *
     * @param indexId the value for sys_dic.index_id
     *
     * @mbggenerated
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.code_
     *
     * @return the value of sys_dic.code_
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.code_
     *
     * @param code the value for sys_dic.code_
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.code_text
     *
     * @return the value of sys_dic.code_text
     *
     * @mbggenerated
     */
    public String getCodeText() {
        return codeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.code_text
     *
     * @param codeText the value for sys_dic.code_text
     *
     * @mbggenerated
     */
    public void setCodeText(String codeText) {
        this.codeText = codeText == null ? null : codeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.enable_
     *
     * @return the value of sys_dic.enable_
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.enable_
     *
     * @param enable the value for sys_dic.enable_
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.sort_no
     *
     * @return the value of sys_dic.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.sort_no
     *
     * @param sortNo the value for sys_dic.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.editable_
     *
     * @return the value of sys_dic.editable_
     *
     * @mbggenerated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.editable_
     *
     * @param editable the value for sys_dic.editable_
     *
     * @mbggenerated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.remark_
     *
     * @return the value of sys_dic.remark_
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.remark_
     *
     * @param remark the value for sys_dic.remark_
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}