package org.shjr.iplat.mybatis.generator.model;

import java.io.Serializable;

public class SysFieldCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.field_id
     *
     * @mbggenerated
     */
    private Integer field_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.code_desc
     *
     * @mbggenerated
     */
    private String code_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.sortno
     *
     * @mbggenerated
     */
    private Integer sortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_field_code.editable
     *
     * @mbggenerated
     */
    private Integer editable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_field_code
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.id
     *
     * @return the value of sys_field_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.id
     *
     * @param id the value for sys_field_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.field_id
     *
     * @return the value of sys_field_code.field_id
     *
     * @mbggenerated
     */
    public Integer getField_id() {
        return field_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.field_id
     *
     * @param field_id the value for sys_field_code.field_id
     *
     * @mbggenerated
     */
    public void setField_id(Integer field_id) {
        this.field_id = field_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.code
     *
     * @return the value of sys_field_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.code
     *
     * @param code the value for sys_field_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.code_desc
     *
     * @return the value of sys_field_code.code_desc
     *
     * @mbggenerated
     */
    public String getCode_desc() {
        return code_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.code_desc
     *
     * @param code_desc the value for sys_field_code.code_desc
     *
     * @mbggenerated
     */
    public void setCode_desc(String code_desc) {
        this.code_desc = code_desc == null ? null : code_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.enable
     *
     * @return the value of sys_field_code.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.enable
     *
     * @param enable the value for sys_field_code.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.sortno
     *
     * @return the value of sys_field_code.sortno
     *
     * @mbggenerated
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.sortno
     *
     * @param sortno the value for sys_field_code.sortno
     *
     * @mbggenerated
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_field_code.editable
     *
     * @return the value of sys_field_code.editable
     *
     * @mbggenerated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_field_code.editable
     *
     * @param editable the value for sys_field_code.editable
     *
     * @mbggenerated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }
}