CREATE DATABASE IF NOT EXISTS `ibase4j_biz`;
USE `ibase4j_biz`;

CREATE TABLE IF NOT EXISTS `t_member` (
  `id_` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(64) DEFAULT NULL COMMENT '姓名',
  `password_` varchar(50) DEFAULT NULL COMMENT '密码',
  `phone_` varchar(11) NOT NULL COMMENT '电话',
  `nick_name` varchar(32) DEFAULT NULL COMMENT '昵称',
  `email_` varchar(32) DEFAULT NULL COMMENT '邮箱',
  `sex_` int(1) DEFAULT '0' COMMENT '性别(0:未知;1:男;2:女)',
  `token_` varchar(256) DEFAULT NULL COMMENT 'APP会话token',
  `uuid_` varchar(128) DEFAULT NULL COMMENT '客户端唯一标识',
  `avatar_` varchar(512) DEFAULT NULL COMMENT '头像',
  `qr_code` varchar(512) DEFAULT NULL COMMENT '二维码',
  `personal_sign` varchar(512) DEFAULT NULL COMMENT '个性签名',
  `id_card` varchar(32) DEFAULT NULL COMMENT '身份证号码',
  `birth_day` date DEFAULT NULL COMMENT '出生日期',
  `wei_xin` varchar(16) DEFAULT NULL COMMENT '微信',
  `wei_bo` varchar(16) DEFAULT NULL COMMENT '微博',
  `qq_` varchar(16) DEFAULT NULL COMMENT 'QQ',
  `is_online` tinyint(1) DEFAULT '0' COMMENT '是否在线',
  `location_country` varchar(6) DEFAULT NULL COMMENT '所在国家',
  `location_province` varchar(6) DEFAULT NULL COMMENT '所在省市',
  `location_city` varchar(6) DEFAULT NULL COMMENT '所在市',
  `location_area` varchar(6) DEFAULT NULL COMMENT '所在区',
  `wx_openId` varchar(64) DEFAULT NULL COMMENT '微信唯一标识',
  `registration_id` varchar(255) DEFAULT NULL,
  `enable_` tinyint(1) DEFAULT '1',
  `remark_` varchar(1024) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `create_by` bigint(20) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_by` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id_`),
  UNIQUE KEY `phone_` (`phone_`),
  UNIQUE KEY `email_` (`email_`),
  UNIQUE KEY `user_name` (`user_name`),
  KEY `sex_` (`sex_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员';