package org.ibase4j.dao.generator;

import java.util.List;
import org.ibase4j.model.generator.SysUserPermission;

public interface SysUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbggenerated
     */
    int insert(SysUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbggenerated
     */
    SysUserPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbggenerated
     */
    List<SysUserPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserPermission record);
}